name: Docker Image Downloader Pro
on: [workflow_dispatch]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Pull and Save Image
        run: |
          docker pull lfoppiano/grobid:latest-full
          # 使用 zstd 高压缩比压缩，并切分成 2GB 一个的小块
          docker save lfoppiano/grobid:latest-full | zstd -1 | split -b 2G - grobid_part_

      - name: Upload Artifact Parts
        uses: actions/upload-artifact@v4
        with:
          name: grobid-parts
          path: grobid_part_*
          retention-days: 1
